[KBV-494] - Fraud error screen
alphagov/di-ipv-cri-fraud-front pull request #39
Opened 2022-06-09 16:28 UTC by ElliotMurphyGDS

### What changed
Updated fraud error screen to match specification for MVP

- [KBV-494](https://govukverify.atlassian.net/browse/KBV-494)

2022-06-09 16:32 UTC, merlinc submitted a review, later dismissed
This is an improvement on what we have now

Two things for us to consider in the future:

- i18n - we need to be able to support the Welsh language (usually done through locale files)
- reuse - it would be nice not to have to copy these files between CRIs

These two aims may not be compatible.

2022-06-09 16:34 UTC, merlinc commented
Oops, you'll need to fix up the browser tests, as they're currently using `getSomethingWentWrongMessage` which no longer applies :)

2022-06-10 10:19 UTC, merlinc requested changes

2022-06-10 10:19 UTC, merlinc commented on test/browser/step_definitions/errors.js
> +  expect(errorTitle).to.equal("Sorry, there is a problem with the service");
The browser tests are using the [Page Object Model pattern](https://martinfowler.com/bliki/PageObject.html) to abstract UI implementation details, using [Playwright's POM](https://playwright.dev/docs/test-pom)

Could you move this text into the error page, using a similar approach to the `getSomethingWentWrongMessage`

2022-06-10 14:51 UTC, merlinc submitted a review, later dismissed

2022-06-10 17:30 UTC, gds-jbentham approved these changes

2022-06-10 17:35 UTC, merged